import { CategoryConfig, Product } from "./types";

export const BRAND_RED = "#CE0028";

export const CATEGORY_CONFIG: Record<string, CategoryConfig> = {
  hoodies: {
    key: "hoodies",
    label: "Hoodies",
    heroImage: "/images/hoodies-hero.jpg",
    heroSubtitle: "Heavyweight fits. Minimal branding. Maximum presence.",
  },
  "t-shirts": {
    key: "t-shirts",
    label: "T-Shirts",
    heroImage: "/images/tshirts-hero.jpg",
    heroSubtitle: "Clean silhouettes. Premium hand-feel. Built different.",
  },
  caps: {
    key: "caps",
    label: "Caps",
    heroImage: "/images/caps-hero.jpg",
    heroSubtitle: "Minimal caps designed to stand out quietly.",
  },
};

export const PRODUCTS: Product[] = [
  /* ======================= T-SHIRTS (10) ======================= */
  {
    id: "ts-01",
    category: "t-shirts",
    name: "Red Graphic Tee",
    price: 45,
    tag: "Drop 01",
    image: "/images/tshirt-1-3d.png",
    availability: "In Stock",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red"],
    fit: "Oversized",
  },
  {
    id: "ts-02",
    category: "t-shirts",
    name: "Creator Black Tee",
    price: 39,
    tag: "New",
    image: "/images/tshirt-2-3d.png",
    availability: "Low Stock",
    sizes: ["M", "L", "XL"],
    colors: ["Black"],
    fit: "Relaxed",
  },
  {
    id: "ts-03",
    category: "t-shirts",
    name: "Night Shift Tee",
    price: 42,
    tag: "Best Seller",
    image: "/images/tshirt-1-3d.png",
    availability: "In Stock",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black"],
    fit: "Oversized",
  },
  {
    id: "ts-04",
    category: "t-shirts",
    name: "Studio Core Tee",
    price: 35,
    tag: "Essentials",
    image: "/images/tshirt-2-3d.png",
    availability: "In Stock",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Off-White"],
    fit: "Regular",
  },
  {
    id: "ts-05",
    category: "t-shirts",
    name: "BLTDIF Chest Logo Tee",
    price: 36,
    tag: "New",
    image: "/images/tshirt-1-3d.png",
    availability: "In Stock",
    sizes: ["S", "M", "L"],
    colors: ["Black"],
    fit: "Regular",
  },
  {
    id: "ts-06",
    category: "t-shirts",
    name: "Heavy Cotton Oversize Tee",
    price: 49,
    tag: "Premium",
    image: "/images/tshirt-2-3d.png",
    availability: "In Stock",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Charcoal"],
    fit: "Oversized",
  },
  {
    id: "ts-07",
    category: "t-shirts",
    name: "Minimal Type Tee",
    price: 33,
    tag: "Essentials",
    image: "/images/tshirt-1-3d.png",
    availability: "In Stock",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White"],
    fit: "Regular",
  },
  {
    id: "ts-08",
    category: "t-shirts",
    name: "Shadow Print Tee",
    price: 44,
    tag: "Limited",
    image: "/images/tshirt-2-3d.png",
    availability: "Low Stock",
    sizes: ["M", "L", "XL"],
    colors: ["Black"],
    fit: "Relaxed",
  },
  {
    id: "ts-09",
    category: "t-shirts",
    name: "Grid Texture Tee",
    price: 41,
    tag: "Drop 01",
    image: "/images/tshirt-1-3d.png",
    availability: "In Stock",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Stone"],
    fit: "Relaxed",
  },
  {
    id: "ts-10",
    category: "t-shirts",
    name: "Built Different Tee",
    price: 38,
    tag: "Best Seller",
    image: "/images/tshirt-2-3d.png",
    availability: "In Stock",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black"],
    fit: "Oversized",
  },

  /* ======================= HOODIES (10) ======================= */
  {
    id: "hd-01",
    category: "hoodies",
    name: "The Shadow Knows Hoodie",
    price: 89,
    tag: "Drop 01",
    image: "/images/hoodie-back-3d.png",
    availability: "In Stock",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Taupe"],
    fit: "Oversized",
  },
  {
    id: "hd-02",
    category: "hoodies",
    name: "Night Shift Hoodie",
    price: 95,
    tag: "Premium",
    image: "/images/hoodie-back-3d.png",
    availability: "In Stock",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Black"],
    fit: "Boxy",
  },
  {
    id: "hd-03",
    category: "hoodies",
    name: "Studio Core Hoodie",
    price: 79,
    tag: "Essentials",
    image: "/images/hoodie-back-3d.png",
    availability: "Low Stock",
    sizes: ["S", "M", "L"],
    colors: ["Grey"],
    fit: "Regular",
  },
  {
    id: "hd-04",
    category: "hoodies",
    name: "BLTDIF Center Chest Hoodie",
    price: 84,
    tag: "New",
    image: "/images/hoodie-back-3d.png",
    availability: "In Stock",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Taupe"],
    fit: "Oversized",
  },
  {
    id: "hd-05",
    category: "hoodies",
    name: "Heavy Fleece Hoodie",
    price: 99,
    tag: "Premium",
    image: "/images/hoodie-back-3d.png",
    availability: "In Stock",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Charcoal"],
    fit: "Boxy",
  },
  {
    id: "hd-06",
    category: "hoodies",
    name: "Minimal Patch Hoodie",
    price: 86,
    tag: "Drop 01",
    image: "/images/hoodie-back-3d.png",
    availability: "In Stock",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Stone"],
    fit: "Regular",
  },
  {
    id: "hd-07",
    category: "hoodies",
    name: "Shadow Backprint Hoodie",
    price: 109,
    tag: "Limited",
    image: "/images/hoodie-back-3d.png",
    availability: "Low Stock",
    sizes: ["M", "L", "XL"],
    colors: ["Taupe"],
    fit: "Oversized",
  },
  {
    id: "hd-08",
    category: "hoodies",
    name: "Zip Hoodie (Essentials)",
    price: 92,
    tag: "Essentials",
    image: "/images/hoodie-back-3d.png",
    availability: "In Stock",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black"],
    fit: "Regular",
  },
  {
    id: "hd-09",
    category: "hoodies",
    name: "Oversized Street Hoodie",
    price: 105,
    tag: "Best Seller",
    image: "/images/hoodie-back-3d.png",
    availability: "In Stock",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Black"],
    fit: "Oversized",
  },
  {
    id: "hd-10",
    category: "hoodies",
    name: "Core Pullover Hoodie",
    price: 76,
    tag: "Best Seller",
    image: "/images/hoodie-back-3d.png",
    availability: "In Stock",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Taupe"],
    fit: "Regular",
  },

  /* ======================= CAPS (10) ======================= */
  {
    id: "cp-01",
    category: "caps",
    name: "Built Different Cap",
    price: 29,
    tag: "Essentials",
    image: "/images/cap-2-3d.png",
    availability: "In Stock",
    colors: ["Burgundy"],
  },
  {
    id: "cp-02",
    category: "caps",
    name: "Studio Logo Cap",
    price: 32,
    tag: "New",
    image: "/images/cap-2-3d.png",
    availability: "In Stock",
    colors: ["Burgundy"],
  },
  {
    id: "cp-03",
    category: "caps",
    name: "Minimal Core Cap",
    price: 27,
    tag: "Best Seller",
    image: "/images/cap-2-3d.png",
    availability: "Low Stock",
    colors: ["Burgundy"],
  },
  {
    id: "cp-04",
    category: "caps",
    name: "Two-Cap Pack",
    price: 49,
    tag: "Value Pack",
    image: "/images/cap-2-3d.png",
    availability: "In Stock",
    colors: ["Burgundy"],
  },
  {
    id: "cp-05",
    category: "caps",
    name: "Shadow Stitch Cap",
    price: 34,
    tag: "Limited",
    image: "/images/cap-2-3d.png",
    availability: "Low Stock",
    colors: ["Burgundy"],
  },
  {
    id: "cp-06",
    category: "caps",
    name: "Everyday Cap",
    price: 26,
    tag: "Essentials",
    image: "/images/cap-2-3d.png",
    availability: "In Stock",
    colors: ["Burgundy"],
  },
  {
    id: "cp-07",
    category: "caps",
    name: "Curve Brim Cap",
    price: 28,
    tag: "Drop 01",
    image: "/images/cap-2-3d.png",
    availability: "In Stock",
    colors: ["Burgundy"],
  },
  {
    id: "cp-08",
    category: "caps",
    name: "Flat Brim Cap",
    price: 31,
    tag: "New",
    image: "/images/cap-2-3d.png",
    availability: "In Stock",
    colors: ["Burgundy"],
  },
  {
    id: "cp-09",
    category: "caps",
    name: "Minimal Type Cap",
    price: 29,
    tag: "Best Seller",
    image: "/images/cap-2-3d.png",
    availability: "In Stock",
    colors: ["Burgundy"],
  },
  {
    id: "cp-10",
    category: "caps",
    name: "Premium Stitch Cap",
    price: 36,
    tag: "Premium",
    image: "/images/cap-2-3d.png",
    availability: "Low Stock",
    colors: ["Burgundy"],
  },
];
